package bf2.model

case class CharacterState(
                           name: String,
                           race: Race,
                           characterClass: CharacterClass,
                           level: Int,
                           gender: String,
                           height: String,
                           weight: Int,
                           age: Int,
                           alignment: CharacterAlignment,
                           personality: String,
                           strength: Int,
                           dexterity: Int,
                           constitution: Int,
                           intelligence: Int,
                           wisdom: Int,
                           charisma: Int,
                           attackBonus: String,
                           meleeBonus: String,
                           rangedBonus: String,
                           acBonus: String,
                           acBase: String,
                           hitPoints: Int,
                           savingThrows: SavingThrows,
                           abilities: String,
                           background: Background,
                           equipment: Equipment,
                           spells: Seq[String],
                           turnUndead: Seq[String],
                           thiefSkills: Seq[String]
                         )

object CharacterState {
  def initialState(): CharacterState = CharacterState(
    name = "unknown",
    race = Human,
    characterClass = Fighter,
    level = 1,
    gender = "Male",
    height = "6'1",
    weight = 180,
    age = 24,
    alignment = Lawful,
    personality = "happy",
    strength = 12,
    dexterity = 12,
    constitution = 12,
    intelligence = 12,
    wisdom = 12,
    charisma = 12,
    attackBonus = "+1",
    meleeBonus = "+1",
    rangedBonus = "+1",
    acBonus = "+0",
    acBase = "10",
    hitPoints = 5,
    savingThrows = SavingsThrows.fighter(1),
    abilities = Human.getAbilities.mkString(","),
    background = Background(),
    equipment = Equipment(),
    spells = Seq.empty,
    turnUndead = Seq.empty,
    thiefSkills = Seq.empty
  )
}
